name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          version: '^11.25'
          runtime: node@24
          cache: true
          require-lockfile: true

      - name: Install Zig
        uses: xyzzylabs/setup-zig@v1
        with:
          version: 0.16.0

      - name: Run lib tests
        run: pnpm test:core

      - name: Run wasm tests
        run: pnpm test:wasm
